// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CommonIcon: typeof import('./components/common/Icon.vue')['default']
    ConsoleLoader: typeof import('./components/console/Loader.vue')['default']
    FooterWrapper: typeof import('./components/footer/Wrapper.vue')['default']
    InfoContent: typeof import('./components/info/Content.vue')['default']
    InfoHeader: typeof import('./components/info/Header.vue')['default']
    InfoSkills: typeof import('./components/info/Skills.vue')['default']
    InfoWrapper: typeof import('./components/info/Wrapper.vue')['default']
    ProjectContent: typeof import('./components/project/Content.vue')['default']
    ProjectSlides: typeof import('./components/project/Slides.vue')['default']
    ProjectTechnologies: typeof import('./components/project/Technologies.vue')['default']
    ProjectWrapper: typeof import('./components/project/Wrapper.vue')['default']
  }
}

export { }
